session-foundation/session-android

app/src/main/java/org/thoughtcrime/securesms/database/MmsDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/database/MmsSmsColumns.java, app/src/main/java/org/thoughtcrime/securesms/database/MmsSmsDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/SearchDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/SmsDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java
This PR adds a `is_deleted` virtual column to the sms/mms so the logic can be reused across varies places.
=> Add "is_deleted" column to sms/mms

scripts/build-and-release.py
This PR fixes up the automated build script.
=> Add fdroid check and fix github release uploads

libsession/src/main/res/values-b+ar+SA/strings.xml, libsession/src/main/res/values-b+cs+CZ/strings.xml, libsession/src/main/res/values-b+de+DE/strings.xml, libsession/src/main/res/values-b+nl+NL/strings.xml, libsession/src/main/res/values-b+pl+PL/strings.xml, libsession/src/main/res/values-b+uk+UA/strings.xml, libsession/src/main/res/values/strings.xml
[Automated]
This PR includes the latest translations from Crowdin
Session uses the community-driven translation platform Crowdin for localization, anyone can contribute at https://getsession.org/translate
=> [Automated] Update translations from Crowdin

app/src/main/java/org/thoughtcrime/securesms/attachments/DatabaseAttachmentProvider.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/database/MessageDataProvider.kt
=> Add missing implementation to delete member's message on swarm

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession-util/src/main/cpp/user_groups.h, libsession-util/src/main/java/network/loki/messenger/libsession_util/util/GroupInfo.kt
- **A thread created locally should not set "date" to current time**
- **Added missing "joinedAt" field for groups**
=> Added missing joined_at for groups

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt
Basically when we receive the instruction to delete message with attachments, exclude link preview and audio message.
=> [SES-2966] - Do not delete link previews or audio message while deleting attachment

.drone.jsonnet
=> Temporary measure for CI

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession-util/src/main/cpp/user_groups.h, libsession-util/src/main/java/network/loki/messenger/libsession_util/util/GroupInfo.kt
Changes to use `mark_kicked` when `kicked == true`, this is to make sure correct flags are set.
=> Use mark_kicked when kicked

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/mention/MentionViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/handler/AdminStateSync.kt, app/src/main/java/org/thoughtcrime/securesms/groups/handler/RemoveGroupMemberHandler.kt, libsession-util/src/main/cpp/group_keys.cpp, libsession-util/src/main/cpp/group_members.cpp, libsession-util/src/main/java/network/loki/messenger/libsession_util/Config.kt, libsession-util/src/main/java/network/loki/messenger/libsession_util/util/GroupMember.kt
The group member status in the libsession has been moved from individual member into the manager class.
=> Integrate the group member status change

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/groups/GroupManagerV2.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/ReceivedMessageHandler.kt
Basically the use of admin key/seed is mixed up.
=> [SES-3192] - Fix unable to receive "invite-ad-admin"

app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/EditGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/EditGroupScreen.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/GroupMembersScreen.kt, libsession-util/src/main/java/network/loki/messenger/libsession_util/util/GroupMember.kt
This PR updates a few sorting rules since we have introduced more member status.
=> [SES-3196] - Incorrect sorting order for group members

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/BatchMessageReceiveJob.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/ReceivedMessageHandler.kt
This PR adds logic to reject 1-to-1 disappearing messages as they aren't authenticated.
=> [SES-3183] - Do not accept 1-to-1 disappearing messages in a group

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/home/PathActivity.kt, app/src/main/java/org/thoughtcrime/securesms/home/PathStatusView.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/SettingsActivity.kt, app/src/main/java/org/thoughtcrime/securesms/util/IP2Country.kt, libsession/src/main/java/org/session/libsession/snode/OnionRequestAPI.kt
This PR replaces the usage of `LocalBroadcastManager` to a `StateFlow` for onion path.
=> Onion paths as a StateFlow

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigUploader.kt
This PR adds a reactive source to config upload so that:
1. The upload process can only start whenever there's a logged in user
2. The upload process will stop whenever the user logs out.
=> [SES-3247] - Fixed crash upon launch

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigUploader.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/utilities/ResendMessageUtilities.kt, app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/EditGroupScreen.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/GroupMembersScreen.kt, app/src/main/java/org/thoughtcrime/securesms/repository/ConversationRepository.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/AttachmentUploadJob.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/InviteContactsJob.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/MessageSendJob.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSenderClosedGroupHandler.kt
- **Fixed crash upon launch (#911)**
- **[SES-3200] - Offline control message improvement (#912)**
=> Merge release 1.21.0 to dev

app/src/main/AndroidManifest.xml, app/src/main/java/org/thoughtcrime/securesms/conversation/start/NewConversationFragment.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenu.kt, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenuViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/CreateLegacyGroupFragment.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/CreateLegacyGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/EditLegacyClosedGroupLoader.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/EditLegacyGroupActivity.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/EditLegacyGroupMembersAdapter.kt, app/src/main/res/layout/activity_edit_closed_group.xml, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModelTest.kt, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/MentionEditableTest.kt, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/MentionViewModelTest.kt, libsession/src/main/java/org/session/libsession/messaging/groups/LegacyGroupDeprecationManager.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/LegacyClosedGroupPollerV2.kt, libsession/src/main/java/org/session/libsession/utilities/NonTranslatableStringConstants.kt, libsession/src/main/java/org/session/libsession/utilities/TextSecurePreferences.kt
This PR adds another state `NOT_DEPRECATING` to indicate we haven't started the deprecation process. 
This state is also a timestamp based test.
To support this state, the legacy group creation is also brought back.
=> [SES-3251] - Add additional deprecation state and bring back legacy group creation

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/org/thoughtcrime/securesms/conversation/start/NewConversationFragment.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenu.kt, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenuViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/CreateLegacyGroupFragment.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/CreateLegacyGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/EditLegacyClosedGroupLoader.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/EditLegacyGroupActivity.kt, app/src/main/java/org/thoughtcrime/securesms/groups/legacy/EditLegacyGroupMembersAdapter.kt, app/src/main/res/drawable/conversation_menu_divider.xml, app/src/main/res/layout/activity_edit_closed_group.xml, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModelTest.kt, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/MentionEditableTest.kt, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/MentionViewModelTest.kt, libsession/src/main/java/org/session/libsession/messaging/groups/LegacyGroupDeprecationManager.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/LegacyClosedGroupPollerV2.kt, libsession/src/main/java/org/session/libsession/utilities/NonTranslatableStringConstants.kt, libsession/src/main/java/org/session/libsession/utilities/TextSecurePreferences.kt
- **Update Signature Verification Instructions and Links (#908)**
- **[SES-3251] - Add additional deprecation state and bring back legacy group creation (#928)**
=> Merge 1.21.0 to dev

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/database/model/MessageRecord.java, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenu.kt, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenuViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/res/layout/view_user.xml, libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageBuilder.kt
[SES-3301](https://optf.atlassian.net/browse/SES-3301) - Fixed display of legacy control messages
[SES-3303](https://optf.atlassian.net/browse/SES-3303) - Proper url for group banner
[SES-3304](https://optf.atlassian.net/browse/SES-3304) - Removing admin state of dialogs for DEPRECATED legacy groups
[SES-3307](https://optf.atlassian.net/browse/SES-3307) - Fixed user view UI
[SES-3308](https://optf.atlassian.net/browse/SES-3308) - Not overwriting the last character in the groups banners
=> QA fixes for Groups V2

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/home/UserDetailsBottomSheet.kt, app/src/main/res/layout/fragment_user_details_bottom_sheet.xml
[SES-3367](https://optf.atlassian.net/browse/SES-3367) - Fix name edit in groups
=> SES-3367 - properly allowing for user name edit in groups

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigUploader.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupPoller.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupPollerManager.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupRevokedMessageHandler.kt, app/src/main/java/org/thoughtcrime/securesms/groups/handler/RemoveGroupMemberHandler.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/PushReceiver.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/PushRegistrationHandler.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/PushRegistryV2.kt, libsession-util/src/main/cpp/util.cpp, libsession-util/src/main/java/network/loki/messenger/libsession_util/Config.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/notifications/Models.kt, libsession/src/main/java/org/session/libsession/utilities/ConfigFactoryProtocol.kt, libsignal/src/main/java/org/session/libsignal/utilities/Namespace.kt
This PR puts in logic in the `PushReceiver` so that when we receive the group config messages as push notification, we merge or handle them properly.
=> Subscribe to group config messages

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java
This is a follow-up PR to enable logging for libsession: https://github.com/session-foundation/session-android/pull/997
=> Enable libsession login

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigUploader.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupPollerManager.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/SettingsActivity.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/SettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/service/WebRtcCallService.kt, app/src/main/java/org/thoughtcrime/securesms/util/NetworkConnectivity.kt
- **Renamed**
- **Update to what counts as connected**
=> [SES-3491] - Update to network connectivity check

app/build.gradle, libsession/src/main/java/org/session/libsession/messaging/groups/LegacyGroupDeprecationManager.kt
Hopefully the last commit for the release
=> Increase version code and update deprecation dates

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageContentView.kt
[SES-3506](https://optf.atlassian.net/browse/SES-3506) - Open documents when tapping messages with attached files
=> SES-3506 open document messages on tap

app/src/huawei/kotlin/org/thoughtcrime/securesms/notifications/HuaweiTokenFetcher.kt, app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, app/src/main/java/org/thoughtcrime/securesms/util/ClearDataUtils.kt, app/src/play/kotlin/org/thoughtcrime/securesms/notifications/FirebaseTokenFetcher.kt, libsession/src/main/java/org/session/libsession/messaging/notifications/TokenFetcher.kt
May have to be in the next release
=> Add resetToken to TokenFetcher

.drone.jsonnet, app/src/website/kotlin/org/thoughtcrime/securesms/notifications/NoOpPushModule.kt, app/src/website/kotlin/org/thoughtcrime/securesms/notifications/NoOpTokenFetcher.kt
...and also adds website/huawei assemble to the CI pipeline, however their artifacts aren't being uploaded atm.
=> Fix website variant build

app/build.gradle, build.gradle, content-descriptions/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, libsession-util/build.gradle, libsession/build.gradle, libsession/src/main/java/org/session/libsession/snode/SnodeAPI.kt, libsession/src/main/java/org/session/libsession/snode/utilities/OKHTTPUtilities.kt, libsession/src/main/java/org/session/libsession/utilities/Address.kt, libsignal/build.gradle
And also update some of the build gradle files
=> Update AGP and a few essential dependencies

.github/workflows/build_and_test.yml, app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, app/src/main/java/org/thoughtcrime/securesms/groups/handler/RemoveGroupMemberHandler.kt
- **Fix a potential crash handling member removal**
- **Change how the class is instantiated**
=> Fix a potential crash when handling member removal offline

app/src/main/java/org/thoughtcrime/securesms/notifications/MarkReadReceiver.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt
This PR catches the API errors at more places so that they don't crash the app.
=> Fix additional play store crashes

app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchAdapter.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchAdapterUtils.kt, app/src/main/java/org/thoughtcrime/securesms/search/model/MessageResult.java
The root cause is the lack of data equality test...
=> [SES-3536] - Fix flashes on search result list

app/src/main/java/org/thoughtcrime/securesms/home/HomeViewModel.kt
We might never know the reason of this one...
=> Fix prod crashes

app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchResult.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchViewModel.kt
[/SES-2588](https://optf.atlassian.net/browse/SES-2588) - Making sure we display "Note to self" when searching for the localised version of the words "note to self"
=> Searching for "Note to self" should show note to self in search results

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageContentView.kt
Fixing alignments of visible message content views
=> SES-3628 - Attachment alignments

app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt
Only sync from config for 1on1 recipients
=> Only removing contacts from 1on1

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java, app/src/main/java/org/thoughtcrime/securesms/groups/ClosedGroupManager.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManager.java, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/OpenGroupManager.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, libsession/src/main/java/org/session/libsession/database/StorageProtocol.kt
[SES-3674](https://optf.atlassian.net/browse/SES-3674) - Fixing syncing issues
=> Updating logic

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt
..so that the order of queuing approval and reply message can be guaranteed
=> Add dependency between approval and reply job

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/input_bar/InputBar.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsNavHost.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsNavigator.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsScreen.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/ContentModule.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/SearchContactActionBottomSheet.kt, app/src/main/java/org/thoughtcrime/securesms/ui/components/ConversationAppBar.kt, app/src/main/java/org/thoughtcrime/securesms/util/RecipientChangeSource.kt, app/src/main/res/layout/view_input_bar.xml, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModelTest.kt, content-descriptions/src/main/res/values/strings.xml
More feature integration for the UCS
=> Updated Conversation Settings screen features

app/src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java, app/src/main/java/org/thoughtcrime/securesms/giph/ui/GiphyActivity.java, app/src/main/java/org/thoughtcrime/securesms/giph/ui/GiphyFragment.java, app/src/main/java/org/thoughtcrime/securesms/scribbles/StickerSelectActivity.java, app/src/main/res/layout/giphy_activity.xml, app/src/main/res/layout/media_preview_activity.xml, app/src/main/res/layout/scribble_select_sticker_activity.xml
This PR replaces all easily replacable instances of ViewPager with ViewPager2.
=> [SES-3778] - Replace ViewPager with ViewPager2

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/res/layout/activity_conversation_v2.xml
=> Add a bottom spacer view for convo screen

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.kt, app/src/main/java/org/thoughtcrime/securesms/BaseActionBarActivity.kt, app/src/main/java/org/thoughtcrime/securesms/ScreenLockActionBarActivity.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/MarkReadReceiver.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/PrivacySettingsPreferenceFragment.kt, app/src/main/java/org/thoughtcrime/securesms/service/ExpirationListener.java, app/src/main/java/org/thoughtcrime/securesms/ui/theme/Themes.kt
By using Lazy so we have better control of the order of initialisation
=> Tweaks dependency start up order

app/src/main/java/org/thoughtcrime/securesms/ScreenLockActionBarActivity.kt, app/src/main/java/org/thoughtcrime/securesms/components/SwitchPreferenceCompat.kt, app/src/main/java/org/thoughtcrime/securesms/disguise/AppDisguiseManager.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/appearance/AppDisguiseSettings.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/appearance/AppDisguiseSettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/appearance/AppearanceSettingsActivity.kt, app/src/main/java/org/thoughtcrime/securesms/ui/components/SessionSwitch.kt, app/src/main/java/org/thoughtcrime/securesms/webrtc/WebRtcCallBridge.kt, app/src/main/res/layout/activity_appearance_settings.xml, app/src/main/res/layout/switch_compat_preference.xml, app/src/main/res/values/styles.xml
1. Add a confirm dialog whenever disguise settings changes
2. Change all Switch on Preference to the compose one
Still waiting for copy coming from crowdin
=> UI tweaks for app disguise settings

app/src/main/java/org/thoughtcrime/securesms/home/PathStatusView.kt
This PR offloads the path db loading to background thread.
=> Make sure hasPath runs in background thread

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageContentView.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/search/SearchBottomBar.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/search/SearchViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsActivity.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsNavHost.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsNavigator.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/ui/Components.kt, app/src/main/java/org/thoughtcrime/securesms/ui/components/ConversationAppBar.kt, app/src/main/java/org/thoughtcrime/securesms/ui/theme/Dimensions.kt, app/src/main/res/layout/view_search_bottom_bar.xml
Updated the search functionality to work with our new compose app bar.
Also fixed some scrolling issue that already existed in the app while searching.
Tweaked text message highlight colours and the glow from our glowview.
Followed the changes as per the [PRD](https://docs.google.com/document/d/1YiJv4IQq1jxPqhqox0AXXfK_T-jDhEZaDxOETHoYWY8/edit?tab=t.0) and the [Figma designs](https://www.figma.com/design/PyU5UB5lWEaqKRBR4jUXIM/Groups-Rebuild---Updated-Conversation-Settings--Post-Release-Chunk-1).
=> Updated Conversation screen - Search

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/components/AlbumThumbnailView.kt
Basically if we are sending message and uri is not empty, even it's not done we know the data is there to show.
=> [SES-3811] - Fix image not showing up immediately when sending

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsDialogs.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsScreen.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/CreateGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/EditGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/ui/Components.kt, app/src/main/java/org/thoughtcrime/securesms/ui/components/ConversationAppBar.kt, app/src/main/java/org/thoughtcrime/securesms/ui/components/Text.kt, content-descriptions/src/main/res/values/strings.xml, libsession/src/main/java/org/session/libsession/messaging/groups/GroupManagerV2.kt
Added the logic and UI for nickname editing and group name and description editing.
=> Updated Conversation Settings: dialogs

app/src/main/java/org/thoughtcrime/securesms/database/LokiMessageDatabase.kt
Basically forgot to add in the message type column to message error table
=> Fix missing table column

app/src/main/java/org/session/libsession/database/MessageDataProvider.kt, app/src/main/java/org/session/libsession/database/StorageProtocol.kt, app/src/main/java/org/session/libsession/messaging/messages/visible/Reaction.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/ReceivedMessageHandler.kt, app/src/main/java/org/session/libsignal/database/LokiMessageDatabaseProtocol.kt, app/src/main/java/org/thoughtcrime/securesms/attachments/DatabaseAttachmentProvider.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/EmojiReactionsView.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageView.kt, app/src/main/java/org/thoughtcrime/securesms/database/LokiMessageDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/database/ReactionDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/database/model/ReactionRecord.kt, app/src/main/java/org/thoughtcrime/securesms/reactions/ReactionDetails.kt, app/src/main/java/org/thoughtcrime/securesms/reactions/ReactionRecipientsAdapter.java, app/src/main/java/org/thoughtcrime/securesms/reactions/ReactionsRepository.kt
Basically use more `MessageId` to avoid mistakes.
=> Fix reactions being put into wrong messages

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/utilities/MentionUtilities.kt
=> [ses-3973] - fix mention wrongly detected

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt
=> [SES-3931] - Only show member count when reciepient is approved

app/build.gradle, app/src/main/java/org/thoughtcrime/securesms/notifications/BackgroundPollWorker.kt
- **Bump release version to 1.24.2**
- **Background poller work shouldn't be cancellable**
=> Release 1.24.2

app/src/main/java/org/thoughtcrime/securesms/notifications/PushRegistrationHandler.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/PushRegistrationWorker.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/PushRegistryV2.kt
So that it can retry on its own forever...
=> Added worker for push notification registration

app/build.gradle.kts
- **Update JDK version to 21**
- **Update JDK version to 21**
=> Update JVM toolchain to 21

app/src/main/java/org/thoughtcrime/securesms/database/MmsDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/database/SmsDatabase.java
=> Revert the changes to disappearing deleted messages

app/src/main/java/org/session/libsession/snode/SnodeAPI.kt, app/src/main/java/org/session/libsignal/utilities/Retrying.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/start/newmessage/NewMessageViewModel.kt
[SES-3447](https://optf.atlassian.net/browse/SES-3447) - More robust ONS resolution.
Making sure to rotate the random snode while retrying.
Also moving to coroutine instead of promises
=> SES-3447 - More robust ONS resolution

app/build.gradle.kts, app/src/debug/kotlin/org/thoughtcrime/securesms/debugmenu/DatabaseInspector.kt, gradle/libs.versions.toml
Some usage of the inspector has changed. 
Also cleaned up compose  dependencies.
=> Update db inspector

app/src/main/java/org/session/libsession/messaging/messages/visible/Attachment.kt, app/src/main/java/org/thoughtcrime/securesms/attachments/DatabaseAttachmentProvider.kt
Future proofing the attachment ID as per the discussion [here](https://discord.com/channels/408081923835953153/1246973280108154961/1405021219945975949)
=> Future proofing attachment ID

app/src/main/java/org/thoughtcrime/securesms/ui/components/ConversationAppBar.kt
Added back top app bar's inset handling, and add one for the search bar
=> Fix app bar jumping

app/src/main/java/org/session/libsession/messaging/open_groups/OpenGroupApi.kt
Because official communities are not subscribed, trying to query their pub key gets nothing. So we pass their key arounds in the APIs.
Note that these APIs are going to be refactored soon so this is temporary measure, later we'll want to do proper dependency injection for the OpenGroupApi class.
=> SES-4512 - Fix official communities not loaded

app/src/main/java/org/thoughtcrime/securesms/home/startconversation/group/CreateGroupScreen.kt
...by preventing the user to tap on the create button while the group is being created.
=> [SES-3548] - Fix duplicated groups being created

app/src/main/java/org/session/libsession/utilities/TextSecurePreferences.kt, app/src/main/java/org/thoughtcrime/securesms/InputbarViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/ShareViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/MessageDetailsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/QuoteView.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageView.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/database/RecipientRepository.kt, app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/EditGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/SelectContactsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/home/ConversationView.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/mediasend/MediaSendViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/messagerequests/MessageRequestView.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/SettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/pro/ProStatusManager.kt, app/src/main/java/org/thoughtcrime/securesms/repository/ConversationRepository.kt, app/src/main/java/org/thoughtcrime/securesms/util/AvatarUtils.kt, app/src/main/java/org/thoughtcrime/securesms/util/UserProfileUtils.kt
This PR changes to use `proStatus` from recipient.
=> Uses pro status from recipient

app/src/main/java/org/session/libsession/snode/OnionRequestAPI.kt
Adding some extra non-penalizing checks  in the onion request error handling to match the iOS code more closely.
=> Adding non penalizing status code to onion request error handling
