session-foundation/session-android

app/build.gradle, app/src/main/java/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java
This PR:
* Makes sure `columnExists` uses `sqlite_xinfo` so that it can look at virtual columns
* Update sqlcipher's version
* 
See https://github.com/diesel-rs/diesel/issues/2912
=> Fix sqlite migration crash

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, libsession/src/main/java/org/session/libsession/database/StorageProtocol.kt, libsession/src/main/java/org/session/libsession/utilities/TextSecurePreferences.kt
This handles the case where the groupsv2 config already exists in the old version of the app, installing groupsv2 app doesn't trigger a groupsv2 sync.
It only needs to trigger a config -> local sync to makes this happen.
=> Handle config migration

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/ControlMessageView.kt, app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/SelectContactsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/CreateGroupScreen.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/EditGroupScreen.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/PrivacySettingsActivity.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/PrivacySettingsPreferenceFragment.kt, app/src/main/java/org/thoughtcrime/securesms/ui/components/AppBar.kt, app/src/main/res/values/styles.xml, content-descriptions/src/main/res/values/strings.xml
[SES-3001](https://optf.atlassian.net/browse/SES-3001) - Proper differentiation between note to self and 1on1 when deleting/hiding
[SES-2936](https://optf.atlassian.net/browse/SES-2936) - Make sure we use annotated strings to bold message in dialog
[SES-3035](https://optf.atlassian.net/browse/SES-3035) - Updated test tags
[SES-2979](https://optf.atlassian.net/browse/SES-2979) - Empty member state when creating groups and case insensitive name sorting
Also added the option to auto scroll to the right preference in the privacy screen, for example when wanting to enable the phone calls
=> SES-3001 - Note to self vs 1on1 delete

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/database/MmsSmsDatabase.java
Whenever the group config indicates that we should delete messages before a specified date, we should mark them as deleted locally.
=> SES-2966 - Fix group message deletion

app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java
When a "thread" is created in database, the "date" defaults to 0 (which is equivalent to disable showing date on home screen). However the offending code always creates a thread with a date sets to current time. This is incorrect, as the date should only be updated later with a message (which the code already does).
=> SES-3036 - Thread should not set default creation time to now

app/src/main/java/org/thoughtcrime/securesms/database/LokiAPIDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsignal/src/main/java/org/session/libsignal/database/LokiAPIDatabaseProtocol.kt
Basically when a member leaves/deletes a group, the polling meta should be cleared from the db, so next time they get reinvited, they start from scratch instead. This way they will have access to all messages that are decryptable.
=> SES-2929 - Fix member not having access to old messages

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/MessageUtilities.kt, app/src/main/java/org/thoughtcrime/securesms/database/model/MessageRecord.java, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
This PR:
1. Clears the group thread when kicked
2. Makes sure the "kicked" control message doesn't have a timestamp (also disable the same for the "destroyed" message)
=> [SES-3050] - Kicked group message state

app/src/main/java/org/thoughtcrime/securesms/database/LokiMessageDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
Preivously when we receive a group invite, we delete the one from swarm immediately, regardless of whether we approve it or not.
Now we only delete it once we approve it, this requires the invite message hash to be saved into db, hence the db change.
The db change doesn't require production migration as this whole table is new in groupsv2.
=> [SES-3078] - Pending group invite not restored correctly

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, app/src/main/java/org/thoughtcrime/securesms/calls/WebRtcCallActivity.kt, app/src/main/java/org/thoughtcrime/securesms/database/model/MessageRecord.java, app/src/main/java/org/thoughtcrime/securesms/database/model/ThreadRecord.java, app/src/main/java/org/thoughtcrime/securesms/notifications/DefaultMessageNotifier.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/NotificationState.java, app/src/main/java/org/thoughtcrime/securesms/notifications/PushManager.kt, app/src/main/java/org/thoughtcrime/securesms/service/KeyCachingService.java, app/src/main/java/org/thoughtcrime/securesms/service/WebRtcCallService.kt, app/src/main/java/org/thoughtcrime/securesms/util/CallNotificationBuilder.kt, app/src/main/java/org/thoughtcrime/securesms/webrtc/CallMessageProcessor.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/Poller.kt
Fix to prevent failure to display call notifications when the device is asleep or locked. Android 12 and above has tightened permissions with regard to starting services, in particular foreground services. As such, this patch wakes the device up in order to start the call service and display an incoming call notification, and may start a full-screen intent for the `WebRtcCallActivity` if necessary.
With two devices running (Alice and Bob) - have Alice call Bob under the following conditions:
- With Bob having the app visible in the foreground,
- With Bob having the app running the background (i.e., dismissed but not closed),
- With Bob having force-closed the app (i.e., manually closed it from the back-stack) but the device is awake,
- With Bob having force-closed the app and then locked …
=> Fix phone call from lock screen

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/PollerFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/ClosedGroupPoller.kt, libsession/src/main/java/org/session/libsession/utilities/ConfigFactoryProtocol.kt
There are issues syncing group message when a member is kicked and reinvited to the group. In order to fix them, these have been done:
1. Once kicked, messages, relevant group configs and polling states must all be cleared
2. Once kicked, group message polling should stop and should not resurrect upon config sync.
3. After approving an invitation, thread needs to be cleared to clean out the manually inserted control messages. As once the real messages come through, they will also contain similar control messages and we don't want them to double up.
=> [SES-2968] [SES-2929] - Fix up misc kicked and re-invited message syncing issues

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/MessageUtilities.kt, app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/model/GroupThreadStatus.kt, app/src/main/java/org/thoughtcrime/securesms/database/model/MessageRecord.java, app/src/main/java/org/thoughtcrime/securesms/database/model/ThreadRecord.java, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageBuilder.kt, libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageData.kt, libsignal/src/main/java/org/session/libsignal/messages/SignalServiceGroup.java
Previously, we used control messages to indicate whether the group is destroyed/kicked. This turns out to be a really bad idea because a message can really screws up the conversation state. For example, if you insert a kicked control message into the conversation when restoring an account, it will appear you have received a new "kicked" message which will be really odd.
The messing up has caused several other bugs so this PR will rectify this issue once for all: basically the `GroupThreadStatus` will be introduced into:
1. `ThreadRecord`, where you display the state of a particular thread. For our case, we will say "You were removed" or "Group is deleted" respectively. The display text comes from a state, not a message.
2. `ConversationActivityV2`, where you can control the "state banner" …
=> Introducing thread status for groups

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
When an group invitation is rejected, also delete the invite from swarm.
=> [SES-3089] - Also delete group invite from swarm when rejecting invitation

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
...so that the manually inserted controll messages can be cleared out to avoid doubling up.
=> [SES-2925] - Clear thread messages before accepting/rejecting group invitation

libsession/src/main/java/org/session/libsession/messaging/jobs/MessageSendJob.kt
In the message sender, before sending messages to groups, group keys must be present, otherwise the message will fail through immediately. Even though it will be retried, it's a unnecessary step to go through.
=> [SES-3090] - Only send group messages after keys obtained

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt
There's some back and forth with this one as I'm working through the right code to delete the right attachments.
It turns out the logic in reverse is much simpler: just checking if we have right attachments.
=> [SES-2966] - Delete the right attachments

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java, libsession/src/main/java/org/session/libsession/database/StorageProtocol.kt
Basically we should never put 0L explicitly into db.
=> [SES-3093] - Fix 1970 timestamp issue

app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, libsession/src/main/java/org/session/libsession/snode/OnionRequestAPI.kt, libsignal/src/main/java/org/session/libsignal/utilities/HTTP.kt
This PR:
1. Makse sure config system is able to handle notification pressure
2. Opens up the concurrency on network requests
=> SES-3111 - Improve overall networking bottleneck

app/src/main/java/org/thoughtcrime/securesms/components/ProfilePictureView.kt
This is to fix an issue where the `ProfilePictureView` may be reused by both single icon and multiple icon mode. If the view was in single icon mode and uses the placeholder image, the same placeholder image later re-used by the multiple icon mode, the placeholder image will be screwed up.
This PR makes sure the placeholder is a different one to avoid this issue.
FYI this is what it looks like to be reused:
=> Do not reuse placeholder drawable

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession-util/src/main/cpp/user_groups.cpp, libsession-util/src/main/java/network/loki/messenger/libsession_util/util/GroupInfo.kt
The key we put into promotion message is wrong, it's supposed to be only the first 32 bytes of the admin key (called a seed). When a member receives promotion, they need to construct the full admin key from the seed.
=> SES-3053 Send only the first 32 bytes of admin key as promotion message

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageView.kt
You can swipe left on message to reply/quote. The icon wasn't positioned properly but should now appear to the right of the quoted message appropriately.
=> Fixing the position of the reply icon

app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/groups/OpenGroupManager.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/ClearAllDataDialog.kt, libsession/src/main/java/org/session/libsession/database/StorageProtocol.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/GroupAvatarDownloadJob.kt, libsession/src/main/java/org/session/libsession/utilities/ProfilePictureUtilities.kt
There are a few places left that still doing `Future.get()` which blocks the default dispatcher. The default dispatcher has finite number of threads available so if they are blocked, other things can get blocked too.
This problem is very apparent in accounts with lots of communities. By changing the blocking behavior into `.await()` we can leverage the use of suspend function instead. Most of the changes already come from a coroutine context.
=> Fix OpenGroup blocking default dispatcher

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/groups/GroupManagerV2.kt
This PR fixes an issue where all admins have left the group, making the group in a "destroyed" state, the user is then unable to delete the group due to error gettings keys.
This PR then bypass all the swarm related operations and delete the conversation directly. Also tidy up the unused flag.
=> Delete a group directly if it's already destroyed

app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/SessionUtilModule.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/handler/DestroyedGroupSync.kt, app/src/main/java/org/thoughtcrime/securesms/groups/handler/RemoveGroupMemberHandler.kt, libsession/src/main/java/org/session/libsession/messaging/MessagingModuleConfiguration.kt, libsession/src/main/java/org/session/libsession/messaging/groups/GroupScope.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/ClosedGroupPoller.kt, libsession/src/main/java/org/session/libsession/snode/SnodeAPI.kt
This PR adds a coroutine utility class called `GroupScope`, to try to limit the async tasks that are specific to a particular group are made sure to run in serial.
This is different from a single thread executor, as this has nothing to do with thread: it means that the concurrency limit is applied on a logical task, for example, even though handling group invite consists of multiple async steps, while a group is handling invite, anything else will be queued waiting for the invitation's async steps complete. This allows for a more reliable operation on groups so that you can't sneak in a group removal during a group invitation.
=> Add a group scope to limit group work concurrency

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageView.kt, app/src/main/java/org/thoughtcrime/securesms/database/LokiMessageDatabase.kt, libsession-util/src/main/cpp/group_members.cpp, libsession-util/src/main/java/network/loki/messenger/libsession_util/Config.kt
The direct cause of the crash is that the `This message was deleted` message's sender  somehow  becomes the group itself.
Drilled down to the actual cause, it's due to the message's type has changed from "outgoing" to "incoming". When a message is outgoing, the "sender address" is the group's address itself. But if it becomes incoming, that address is then wrong (meaning somehow group has become the thing that sends message, which is totally wrong).
This PR does two things:
1. Correct the place where the flag flip actual happens (this is an oops: the right data to use on `MmsDatabase` should be `MESSAGE_BOX` rather than `MESSAGE_TYPE`)
2. Wraps the C++ exception so that we can handle this more nicely.
=> [SES-3153] - Fix crash when admin deletes our attachment

app/src/main/java/org/thoughtcrime/securesms/database/LokiMessageDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt
The direct cause is: __No server hash is found for the messages to be deleted__
The root cause is: __when receiving messages with attachments, we wrongly regard it as a plain text message hence inserting the hash into a wrong table__
This PR also gets rid of the use of the `loki_message_hash_table`
=> [SES-3154] - Fix group admin unable to delete message with attachments

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/Poller.kt, libsession/src/main/java/org/session/libsession/snode/SnodeAPI.kt
In groupsv2, whenever a member gets promoted to admin, they should reset the "lastHash" on the poller so that they receive all the historic messages.
However, this PR also includes another change in du-duplication logic, the reason being: previously, when a message is received, our app checks if this message has been received before, then decrypt it. The order of the logic here prevents us from receiving all the historic messages, as the historic messages received before were actually marked as received, despite being unable to decrypted. So even when we are promoted and receive the messages from beginning but these messages are wrongfully treated as duplicates.
This PR hence includes a change of the order: the messages will be decrypted first, then being looked at if they are duplicates.
=> Reset last hash on promotion

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
The problem is the poller is unable to start when the group doesn't have the approriate state in the config. This PR adjusts the order so that the config is updated first, then start the poller.
=> [SES-3202] - Fix group unable to poll when accepting invitation

app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt
Previous work on this "unread count not cleared when admin deletes group" was flawed and not working correctly.
The only way to clear the unread count seems to be set the `UNREAD_COUNT` column directly, which is what `threadDb.setRead` is doing.
=> [SES-3119] - Unread count not cleared

libsession/src/main/java/org/session/libsession/messaging/messages/visible/Attachment.kt
Fix: Provides a filename based on the `AttachmentId` for images associated with link previews. This prevents a NullPointerException because filenames are now mandatory - and link previews now work properly again.
=> Fix link preview images so that they have filenames

app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/database/model/MessageRecord.java, app/src/main/java/org/thoughtcrime/securesms/database/model/ThreadRecord.java, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/home/ConversationView.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeAdapter.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeDiffUtil.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeViewModel.kt, libsession/src/main/java/org/session/libsession/database/StorageProtocol.kt, libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageBuilder.kt, libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageData.kt
This PR:
1. Removes the previously-added hack into conversation list view
2. Adds back the control messages for leaving groups. So now we will have "leaving" and "Error leaving xxx".
=> [SES-2960] - Control messages for leaving groups

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
Rule has changed that when an admin creates a group, they should also see the invitation. Preivously the rule was to show the empty convo state.
With this rule change the logic has become simpler so we always have that invitation message.
=> [SES-2997] - Show "xxx is invited" upon group creation

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt
This PR fixes an incorrect usage of sendChannel: when there's no one caring about the channel the `send` will get blocked. Because now home screen no longer listens for the
group status update (it's updated through control message now), the leaving process gets blocked trying to send the state through the channel. Changing it to `trySend` so that
it doesn't block.
=> [SES-3238] - Fix unable to leave group on home screen

libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageBuilder.kt
Basically in a conversation where you can see you were removed from the group in the past, you are supposed to see "You were removed from the group".
But if you are just kicked and not invited back, the status showing on the thread should say "You were removed from [group_name]".
We have been always using the second version for all the place, this PR hence only corrects the first case.
=> [SES-2924] - Fix incorrect version of "you were removed" used

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/ControlMessageView.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
This PR fixes:
1. Color polluting on "Failed to leave XX" message. Some remnant code that renders a control message red but forgets to set it back. However this code is not longer in used as the message itself comes formatted.
2. "Leaving" control message need to be removed upon failure.
=> [SES-2960] - Fix issues on group leaving control messages 

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/utilities/ResendMessageUtilities.kt, app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/EditGroupScreen.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/GroupMembersScreen.kt, app/src/main/java/org/thoughtcrime/securesms/repository/ConversationRepository.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/AttachmentUploadJob.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/InviteContactsJob.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/MessageSendJob.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSenderClosedGroupHandler.kt
This PR includes a series of improvement:
1. Renamed `MessageSender.sendXXX` methods to reflect what they do more accurately
2. Almost all group control messages are now sent through the job system so they can survive the offline (and retry)
3. Add a result callback into `MessageSendJob` so we can track how they these jobs' status
4. Fix a bug in displaying member status: whether the `Pending removal` is shown or not **DOES NOT** depend on whether that person is admin, rather, it's dependent on whether **I** am an admin.
=> [SES-3200] - Offline control message improvement

app/src/main/java/org/thoughtcrime/securesms/database/model/MessageRecord.java, app/src/main/java/org/thoughtcrime/securesms/home/HomeViewModel.kt, libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageBuilder.kt
This PR:
1. Fetches a group member's name from the group config when it can't be found in the contact system
2. Updates the home page whenever the group config updates (so that the member name can be updated).
=> [SES-3248] - Using member names in the control messages wherever possible

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenu.kt, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenuViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/AppModule.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/SessionUtilModule.kt, app/src/main/java/org/thoughtcrime/securesms/groups/ClosedGroupManager.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/BackgroundPollWorker.kt, app/src/main/java/org/thoughtcrime/securesms/util/DateUtils.kt, libsession/src/main/java/org/session/libsession/messaging/MessagingModuleConfiguration.kt, libsession/src/main/java/org/session/libsession/messaging/groups/LegacyGroupDeprecationManager.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSenderClosedGroupHandler.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/ReceivedMessageHandler.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/LegacyClosedGroupPollerV2.kt, libsession/src/main/java/org/session/libsession/utilities/NonTranslatableStringConstants.kt, libsession/src/main/java/org/session/libsession/utilities/TextSecurePreferences.kt, libsession/src/main/res/values/strings.xml
New features are being added into the group release:
1. The legacy groups will now have two states: pre and post deprecated. Different states present different UI. 
2. A pre-deprecated legacy group will mostly have warnings at place. The warning text varies between non-admin and admins
3. A post-deprecated legacy group will become read-only and inactive (no polling, etc.)
4. A simple migration "shortcut" will be provided to create a new group with the same name/members from the legacy groups.
To avoid making even bigger PR, this PR will address #1-#3. The UI change will be in another PR.
This PR:
1. Intoduces a `LegacyGroupDeprecationManager` where the deprecation state is centrally managed.
2. Fully dependency-inject the `LegacyClosedGroupPollerV2` so that it cake take in the …
=> [SES-3251] - Legacy group migration - Part I

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationReactionOverlay.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationV2Dialogs.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/groups/CreateGroupFragment.kt, app/src/main/java/org/thoughtcrime/securesms/groups/CreateGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/SelectContactsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/compose/CreateGroupScreen.kt, app/src/main/java/org/thoughtcrime/securesms/home/ConversationOptionsBottomSheet.kt, app/src/main/java/org/thoughtcrime/securesms/util/PaddedImageSpan.kt, app/src/main/res/layout/activity_conversation_v2.xml
This PR is Part II work of SES-3251: 
1. Add a button, a confirmation dialog and create group dialog for re-create a legacy group
2. Show/hide options for threads/messages according to deprecation state
=> [SES-3251] - Add recreate group UI and show/hide thread/message options accordingly

libsession/src/main/java/org/session/libsession/snode/SnodeAPI.kt, libsession/src/main/java/org/session/libsession/snode/SnodeClock.kt
This is due to a wrong clock source is used for the `SnodeClock`.
=> Fix a clock drift when the device is in deep sleep

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/EditGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/handler/CleanupInvitationHandler.kt
This PR:
1. Removes blocking dialogs from a few places
2. Makes sure config is sync before sending out invitations
3. Cleans up pending state upon launch
=> [SES-3270] - Group invitation tweaks

app/src/main/java/org/thoughtcrime/securesms/conversation/start/newmessage/NewMessageViewModel.kt
[SES-3280](https://optf.atlassian.net/browse/SES-3280) - Make sure data is punyencoded before ONS lookup
=> Making sure we puny-encode data before ons lookup

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
This is a follow-up change to SES-3200 where that in all the admin operations which can be done offline, should show a control message regardless of failure.
This PR adds such behavior.
=> [SES-3200] - Send rename/promote control message locally

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
Basically rekey is always needed for invitation to work more reliably.
=> [SES-3298] - Rekey always to be performed regardless of sharing history or not

libsession/src/main/java/org/session/libsession/messaging/utilities/UpdateMessageBuilder.kt
There are more cases in `UpdateMessageBuilder` that need to be using `getGroupMemberName`.
=> [SES-3248] - Fix group member name not showing

app/src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java, app/src/main/java/org/thoughtcrime/securesms/contacts/ContactSelectionListFragment.kt, app/src/main/java/org/thoughtcrime/securesms/contacts/ContactSelectionListLoader.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationReactionOverlay.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/MessageDetailActivity.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/MessageDetailsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationActionModeCallback.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationMenuHelper.kt, app/src/main/java/org/thoughtcrime/securesms/home/ConversationOptionsBottomSheet.kt, app/src/main/java/org/thoughtcrime/securesms/reactions/ReactionRecipientsAdapter.java, app/src/main/java/org/thoughtcrime/securesms/reactions/ReactionViewPagerAdapter.java, app/src/main/java/org/thoughtcrime/securesms/reactions/ReactionsDialogFragment.java, libsession/src/main/java/org/session/libsession/messaging/groups/LegacyGroupDeprecationManager.kt
This PR adds logic to hide "write" actions for legacy group in these places:
1. Showing an image in the message (so you can't delete an image from legacy group)
2. Showing destination to share stuff into (so read-only legacy groups shouldn't be in them)
3. Message details (so you can't delete it from there)
4. Long press message context (so you can't delete from there)
5. Convo screen (so you can't invoke menu options at all for legacy group)
6. Removing/adding reaction
Also tidy up the code around checking deprecated state.
=> [SES-3300] - More place to hide message/convo actions based on deprecated state

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt
Basically now we don't want the admin promotion to automatically retry, we need to go back to the non-durable version of `MessageSender.send` so that it doesn't get into the job system.
=> [SES-3319] - No promotion retry in the background

app/src/main/java/org/thoughtcrime/securesms/groups/EditGroupViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/groups/GroupManagerV2.kt
Apart from what the title says, this PR also adds in the whether "history was shared" info when re-inviting a member.
=> [SES-3200] - Do not send control message for re-invite/re-promote

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/util/DateUtils.kt
...So that we also show the time for the deprecated time, to reduce confusion.
=> Updated time format for deprecated time

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt
[SES-3333](https://optf.atlassian.net/browse/SES-3333) - Unblock banner shows confirmation dialog first
=> Making sure the unblock banner shows the dialog first

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt
We have mulitple places that try to sync the group name to local database using different sources. So the group name can come from group configs, it can also come from the user groups config. The source-of-truth is the group config so whenever that updates, also updates the user groups config so they can keep in sync.
=> [SES-3340] - Update user config whenever group name changes

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigUploader.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession-util/src/main/java/network/loki/messenger/libsession_util/Config.kt, libsession/src/main/java/org/session/libsession/utilities/ConfigFactoryProtocol.kt
Previously in the group creation process, the creation will write to the config immediately so even if the user is offline, the creation succeeds. But it creates UX issue while offline. To align this behavior with other platform, this PR:
1. Pulled out some of the config pushing process so that it can be done manually.
2. Only when the config pushing process completes successfully, we proceed to update our configs
This PR also fixes an issue where the first control message sent by the group admin is lost: due to thread not created promptly.
=> [SES-3352] - Create group as a rollback-able process

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationAdapter.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/input_bar/InputBar.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/input_bar/InputBarButton.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/input_bar/InputBarRecordingView.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageViewDelegate.kt, app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/mediasend/MediaRepository.java, app/src/main/java/org/thoughtcrime/securesms/util/GlowView.kt
**Ticket:**
SES-2145
**Adjustments:**
1.) Prevent re-scroll to bottom of conversation after clicking on the message snippet of the original message in a reply. We now smooth scroll to the original message to match iOS behaviour rather than performing an instant scroll which left the recycler view immediately in `SCROLL_STATE_IDLE` and allowed the scroll-to-last-message functionality to be triggered.
2.) Added highlight on successful scroll to original "replied-to" message to match iOS behaviour.
3.) Converted a few methods into expression-bodied equivalents as I came across them as there's no reason not to save some vertical real-estate when we can.
**Potential test steps:**
1.) Reply to a message which is on-screen then click the original message snippet in your reply - original message …
=> SES-2145 - Fix re-scroll to bottom after clicking on original message in a reply

app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession-util/src/main/cpp/group_keys.cpp, libsession-util/src/main/java/network/loki/messenger/libsession_util/Config.kt, libsession/src/main/java/org/session/libsession/utilities/ConfigFactoryProtocol.kt
Previously, when a member is promoted to admin, we recreate the group configs so that it loads the admin key. However there's a better way to do it by just calling `load_admin_key`...
=> Changes to use load_admin_key

libsession-util/src/main/cpp/CMakeLists.txt
Disabled the onion request (and libQuic) code in `libSession`
This seems to build locally when pointing to my `libQuic` branch but will leave this as a draft PR until after https://github.com/session-foundation/libsession-util/pull/6 has been merged
=> Fixes for libQuic merge

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/MessageDetailActivity.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/MessageDetailsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/database/model/DisplayRecord.java, app/src/main/java/org/thoughtcrime/securesms/ui/Strings.kt
Fix:
- Only show the "Received" field in Message Info for incoming messages,
- Only show the "Sent" field in Message Info for outgoing sent messages (for messages which are _Sending_ we show the TitledText "Sending..." with no second line containing the sent/received Date/Time).
- Do not show any Sending / Sent / Received data for messages which have failed to send. For these messages we show a TitledText of "Error:" with the actual error message as the second line.
Potential test steps:
- Successfully send a message, long-press on the message and view the Message Info, observe that the **Sent:** data exists with the correct timestamp,
- Send a MMS message such as a GIF then quickly long-press on the message to view the Message Info, observe that there is no "Sent:" or "Received:" …
=> Fix/SES-1789 Message info for send and receive

libsession-util/src/main/cpp/group_keys.cpp
Catch the CXX exception and turn it to a Java one
=> Fixes crash on unexpected key messages

app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt
We shouldn't remove ourselves from the list when cycling through the contacts
=> Making sure we don't delete a NTS on restore

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, app/src/main/java/org/thoughtcrime/securesms/debugmenu/DebugMenuViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/PushReceiver.kt, app/src/main/java/org/thoughtcrime/securesms/onboarding/messagenotifications/MessageNotificationsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/preferences/ClearAllDataDialog.kt, app/src/main/java/org/thoughtcrime/securesms/util/ClearDataUtils.kt, app/src/play/kotlin/org/thoughtcrime/securesms/notifications/FirebaseTokenFetcher.kt, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModelTest.kt
This PR contains two fixes:
1. To request a new FCM token on log out so you don't receive anything from previous session
2. To skip handling of all group related notification if the group is not active
=> [SES-3434] - Fix receiving left groups' notification

libsession/src/main/java/org/session/libsession/messaging/jobs/JobQueue.kt
Previously, when an attachment upload job completes, it tries to resume the `MessageSendJob` so that the `MessageSendJob` can check if all attachments have been uploaded. The problem is, if then the `MessageSendJob` finds out there are still attachments to upload, the resuming from `AttachmentUploadJob` will no longer trigger a `MessageSendJob`, hence no one is going to send the message out. The issue is a fix back in 2021 where a `pending tasks` set was introduced to try to fix duplicated message issue, and accidentally limit the number of times the `MessageSendJob` could be brought back. 
The fix is properly updating the `pending job` so that the `MessageSendJob` can get executed again on the final attachment upload.
=> [SES-3427] - Fix problem resuming message send job when upload completes

app/src/main/java/org/thoughtcrime/securesms/util/UsernameUtilsImpl.kt, app/src/main/res/layout/view_conversation_action_bar.xml
We should never display a user's name if they are set to their sessionId. We should truncate it instead
https://optf.atlassian.net/browse/QA-1034
=> SES-2113 - Never display a username that matches that user's id. 

app/src/main/java/org/thoughtcrime/securesms/groups/GroupPoller.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupPollerManager.kt, app/src/main/java/org/thoughtcrime/securesms/util/ThrowableUtil.kt, libsession/src/main/java/org/session/libsession/snode/SnodeAPI.kt, libsession/src/main/java/org/session/libsession/snode/model/BatchResponse.kt
Basically this:
1. Take a node from a pool of swarm nodes randomly on each poll
2. Re-fill the pool with all the swarm nodes upon emptied-out
3. Removes a snode with server error from the swarm nodes so it will never get reached in this cycle
=> Group poller tweaks

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.java, app/src/main/java/org/thoughtcrime/securesms/notifications/OptimizedMessageNotifier.java, app/src/main/res/layout/view_input_bar.xml, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/Poller.kt, libsession/src/main/java/org/session/libsession/snode/SnodeAPI.kt
Reworked the poller as the logic wasn't correctly rotating across snodes beyond on exception thrown, which caused issues when landing on a snode with no data, which isn't an exception.
Moved away from Promises in favour of coroutines
=> Polling node rotation

libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/Poller.kt
This PR fixes a crash where you go into the app while you are offline. The root cause is that when the 1on1 poll starting, it calls `getSwarm`, however it's outside our `try..catch...` block for the polling logic, hence the exception flows to the top and crashes the app.
The fix should be pretty safe itself.
=> Move getSwarm into try catch

app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchInputLayout.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchViewModel.kt
This PR reworks the state management for showing/hiding the search screen. Now a dedicated view model state is used to indicate whether the search screen should be shown.
=> [SES-3536] - Unable to navigate back on search screen

app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml
The root cause is the empty view is directly manipulated by the search home screen.
Ideally we want the search views and non-search views to be updated uniformly: if you are on search view, the container for the non-search view should be hidden and vice-versa.
Also replace RelativeLayout with FrameLayout
=> Fix empty state showing up on home screen

app/src/main/java/org/thoughtcrime/securesms/notifications/RemoteReplyReceiver.java, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt
Basically the reply code should have the message ID set after inserting into the db.
=> [SES-3564] - Fix crash replying on push notification

app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, libsession/src/main/java/org/session/libsession/messaging/jobs/InviteContactsJob.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/MessageSender.kt
Basically you can't assume we always have `threadId` for a message.
=> [ses-3567] - fix error sending group invite

app/src/main/java/org/thoughtcrime/securesms/configs/ConfigUploader.kt, libsession/build.gradle
This PR catches the config push exceptions and log them instead.
=> Fix "config too large" crash

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/MessageDetailsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ViewUtil.java, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/AttachmentControlView.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/DocumentView.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/media/DocumentsPage.kt, app/src/main/java/org/thoughtcrime/securesms/webrtc/CallViewModel.kt, app/src/main/res/layout/view_attachment_control.xml, libsession/src/main/java/org/session/libsession/utilities/Util.kt
[SES-3599](https://optf.atlassian.net/browse/SES-3599) - Updated UI for failed download.
Should now match this look:
=> New ui for failed attachment control

app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/migration/DatabaseMigrationManager.kt, app/src/main/java/org/thoughtcrime/securesms/migration/DatabaseMigrationScreen.kt, app/src/main/java/org/thoughtcrime/securesms/util/ClearDataUtils.kt
This PR is to fix this issue on migration error screen: tapping on "clear data" does nothing. See QA-1477.
There are two issues here:
1. As all database access is blocked waiting on error screen, and the config system was  holding a lock while accessing the db, the "clear data" unfortunately will also need access to the config system. The lock then become a deadlock. The solution here is to remove the lock while creating the config from db. 
2. The use of Default dispatcher might not be ideal as all default dispatcher threads are blocked waiting on db. Here for clearing the data, we'll need to use the unconstrained IO dispatcher.
=> Fix deadlock clearing data on migration failure

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.kt, app/src/main/java/org/thoughtcrime/securesms/database/LokiAPIDatabase.kt, libsession/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/Poller.kt, libsession/src/main/java/org/session/libsession/utilities/TextSecurePreferences.kt, libsignal/src/main/java/org/session/libsignal/database/LokiAPIDatabaseProtocol.kt
Previously, if the Android app sees multi part/invalid config, it will ignore it. With the new multipart config, we'll have to refetch all config messages so we get the chance to process them. This only needs to be done once after updating to the latest app version
=> [SES-3731] - Fix multi part config not showing up 

app/src/main/java/org/thoughtcrime/securesms/database/GroupDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchAdapter.kt, app/src/main/java/org/thoughtcrime/securesms/home/search/GlobalSearchViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/search/SearchRepository.kt
This PR fixes a few search related issues:
1. Removes previous restriction on the search result of a contact: needs to have messages with them to display them on search screen.
2. Removes the ability to search for a legacy group by its member. The code there is broken and we shouldn't invest new effort to fix the deprecated code.
3. Some general performance improvement to varies places where redundant allocations are performed, and optimise the search result diff dispatch logic so that big data set doesn't get stuck on UI.
=> Fix search issues

app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java
This was due to previous decision to remove the "message count != 0" condition on getting message request list.
It seems like in this scenario "message count != 0" is actually a valid condition as you would have to have something sent to you to show up as a message request.
=> [SES-3740] - Fix "message requests" not showing

app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt
We use to call `updateEmptyState` when you close search screen, but we have tidied up the view model, the home screen's state has nothing to do with search anymore, so it's actually harmful to call the `updateEmptyState` from the search's perspective: so in previous refactoring of search screen, the `setSearchShown` is tied to the view model's state so it gets called even when you haven't done anything to the search (it's to make sure we execute the UI states needed for a "hidden" search).
This PR removes the empty state meddling from the search logic and now it shows the right screen.
=> Fix empty state showing incorrectly

app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml
This PR is to remove the "animateLayoutChanges" change made recently and add back the old home animation, where it just fades in from search
=> Fix up home/search animation

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/repository/ConversationRepository.kt
The underlying issue:
> The direct cause is when someone approves you with a message, they send an approve message + reply message. Normally you'll receive them in order. But with push notification enabled, they can be out of order, so you receive the reply message first, then the approve message. If we receive a reply message, we know that person has approved you and we mark it so. Then once we process the approval message, we decide not to show it because that person was "approved" before. It's coming from the delete contact logic.
There are multiple places we can attack this problem, but a simplest one for now is to make sure we send the approval + reply messages in a strong order so they have much less chance to go out of order on the receiving side.
Technically there's nothing we can …
=> [SES-3743] - Fix message request approval message not showing

app/build.gradle, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/repository/ConversationRepository.kt, app/src/main/res/layout/activity_home.xml
- **Bump version to 1.23.0**
- **Fix empty state showing incorrectly (#1117)**
- **Fix up animation (#1119)**
- **[SES-3743] - Fix message request approval message not showing (#1118)**
- **Add dependency between approval and reply job (#1120)**
=> Bring release/1.23.0 to dev

app/src/main/java/org/thoughtcrime/securesms/components/SwitchPreferenceCompat.kt, app/src/main/java/org/thoughtcrime/securesms/disguise/AppDisguiseManager.kt
This PR fixes:
1. App not closed on lower Android version: we force finishing the current activity to emulate the closing.
2. The styling of the switches are wrong: it's missing all the default styling. Added a default style attribute fixes the issue.
=> App disguise bug fixes

app/src/main/java/org/thoughtcrime/securesms/database/LokiMessageDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/PushReceiver.kt
Dangerous mistake where `MessageId.toString()` is used instead of `MessageId.id.toString()`.
=> Fix unable to react on community messages

app/src/main/java/org/session/libsession/database/StorageProtocol.kt, app/src/main/java/org/session/libsession/messaging/jobs/BackgroundGroupAddJob.kt, app/src/main/java/org/session/libsession/messaging/open_groups/OpenGroupApi.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/OpenGroupPoller.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/OpenGroupPollerManager.kt, app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.kt, app/src/main/java/org/thoughtcrime/securesms/configs/ConfigToDatabaseSync.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationReactionOverlay.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/dialogs/JoinOpenGroupDialog.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/menus/ConversationActionModeCallback.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageView.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/database/GroupDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/AppModule.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManager.java, app/src/main/java/org/thoughtcrime/securesms/groups/JoinCommunityFragment.kt, app/src/main/java/org/thoughtcrime/securesms/groups/OpenGroupManager.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeActivity.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/BackgroundPollWorker.kt, app/src/main/java/org/thoughtcrime/securesms/notifications/OptimizedMessageNotifier.java, app/src/test/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModelTest.kt
This PR:
1. Clean up the logic behind `OpenGroupPoller`: now we are doing automatic state handling based on configs
2. Change a few classes to use dependency injection 
3. Actually fix up the slow community initial  show up
=> [SES-3538] - Clean up community related classes

app/build.gradle.kts, app/src/main/java/org/session/libsession/database/StorageProtocol.kt, app/src/main/java/org/session/libsession/messaging/jobs/BatchMessageReceiveJob.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/ReceivedMessageHandler.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/OpenGroupPoller.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/OpenGroupPollerManager.kt, app/src/main/java/org/session/libsession/utilities/Util.kt, app/src/main/java/org/thoughtcrime/securesms/database/ReactionDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/database/SmsDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java, app/src/main/java/org/thoughtcrime/securesms/groups/OpenGroupManager.kt
This PR improves the following areas:
1. Reuse some expensive data (like blinded id, user key, etc)
2. Reactions are now updated in one db transaction
=> Improve community loading performance

app/src/main/java/org/session/libsession/database/StorageProtocol.kt, app/src/main/java/org/session/libsession/utilities/ConfigFactoryProtocol.kt, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/dependencies/ConfigFactory.kt, app/src/main/java/org/thoughtcrime/securesms/groups/BaseGroupMembersViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupLeavingWorker.kt, app/src/main/java/org/thoughtcrime/securesms/groups/GroupManagerV2Impl.kt, app/src/main/java/org/thoughtcrime/securesms/groups/handler/DestroyedGroupSync.kt
The cause of the issue SES-3834 is: when destroying a group, the handler `DestroyedGroupSync` is listening for that and deleting all local messages immediately, which is technically correct, but in the case where you initiate the destruction, you should wait until the config is pushed until you can do it.
So the main change here is: add a `fromMerge` flag into the group config change notification event, so `DestroyedGroupSync` only clear the message when it's coming from the config merge.
Another change along with this PR is to move all the group leaving logic into a worker so that it can survive app restarts.
=> [SES-3834] - Leaving group tidy up

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsDialogs.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/settings/ConversationSettingsViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeDialogs.kt, app/src/main/java/org/thoughtcrime/securesms/home/HomeViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/pro/ProStatusManager.kt, app/src/main/java/org/thoughtcrime/securesms/ui/Components.kt
Existing users with already more than the max pins should see a different string in the CTA
=> Crowdin string and string logic for grandfathered users

app/src/main/java/org/session/libsession/messaging/sending_receiving/ReceivedMessageHandler.kt, app/src/main/java/org/session/libsession/utilities/recipients/Recipient.java, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/utilities/AttachmentManager.java, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/mediasend/MediaSendActivity.kt
[SES-4182](https://optf.atlassian.net/browse/SES-4182) - Preserving the char limit state
[SES-4181](https://optf.atlassian.net/browse/SES-4181) - Preserving the message body when sending a camera photo
Other changes were made to avoid changing the recipient class when the values are already the same. The helps avoid the conversation reloading too often for no reason
=> Char limit input issues

app/src/main/java/org/thoughtcrime/securesms/mediasend/MediaSendFragment.kt
[SES-4180](https://optf.atlassian.net/browse/SES-4180) - Preserve input text before picking new media
=> SES-4180 - Preserve text state in media send

app/src/main/java/org/thoughtcrime/securesms/ApplicationContext.kt, app/src/main/java/org/thoughtcrime/securesms/database/ThreadDatabase.java
There is tricky dependency that can't be satifisied during construction of `ThreadDatabase` so the migration has to be post-init.
=> Make sure migration is only done outside ThreadDatabase's constructor

app/src/main/java/org/thoughtcrime/securesms/database/MmsDatabase.kt
Basically a wrong condition is set. Only when `expiryStarted == dateSent` the expiry mode is AfterSend.
=> [SES-4225] - Fix migration issues on disappearing control messages

app/src/main/java/org/thoughtcrime/securesms/database/MmsDatabase.kt, app/src/main/java/org/thoughtcrime/securesms/database/SmsDatabase.java, app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt, app/src/main/java/org/thoughtcrime/securesms/service/ExpiringMessageManager.kt
Forgot to actually improve the logic after the refactoring task. This PR contains fixes as:
1. If messages are being marked as deleted, clear their `expiryStarted`/`expiresIn` so they won't be gone [SES-4224].
2. Start expiring of call messages as soon as they are created, as they aren't real messages sending through [SES-4227]
3. When a message is received/sent, use current time instead of date sent as the expiry started time [SES-2449]
=> Disappearing messages fixes

.drone.jsonnet, .github/workflows/build_and_test.yml, scripts/drone-static-upload.sh
The two variants `automaticQa` and `qa` can't be built together at the same time as they share same package id.
Also:
- Fixes caching issue (incorrect cache key) on Github Action builds
- Tidy up drone CI build script
=> Fix CI build

app/src/main/java/org/thoughtcrime/securesms/home/ConversationOptionsBottomSheet.kt
[SES-4230](https://optf.atlassian.net/browse/SES-4230)
Added a branch to handle legacy group long press.
=> SES-4230 : Tap and hold on a old group v1 entry does not trigger menu (unable not remove it)

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/util/UserProfileUtils.kt
[SES-4292](https://optf.atlassian.net/browse/SES-4292) - Fixed a crash in communities where the community members tapp would try to open the closed group members page. It instead goes to the UCS
[SES-4296](https://optf.atlassian.net/browse/SES-4296) - Truncating long names for the UPM tooltip
=> 1.27.0  fixes

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/mention/MentionViewModel.kt
Fixes based on [QA feedback](https://optf.atlassian.net/browse/QA-2179?focusedCommentId=18668).
Community mentions should be ordered by most recent message sent instead of by name. By-name ordering is retained for groups.
Contacts database somehow messes up the list so to maintain the order by which members are retrieved, it was mapped from memberIDs.
=> SES-3437 : Community Mentions Inconsistent

app/src/main/res/layout/activity_appearance_settings.xml
Added missing horizontal margin for Classic Dark's divider in Appearance screen
=> SES-4269 : Inconsistent Separator Length Theming

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/MessageDetailActivity.kt
Quick fix to use the correct string in the message details
=> Wrong string for message details

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/util/adapter/RecyclerViewUtils.kt
This PR fixes a scrolling issue when the soft keyboard is visible and pressing the _scroll to bottom button_.
This PR adds some extension functions:
`RecyclerView.applyImeBottomPadding()` that applies padding relative to the IME
`RecyclerView.handleScrollToBottom()` that handles the scrolling logic and respects the soft keyboard
https://github.com/user-attachments/assets/ecc44fda-5b01-4cf4-b0b1-982df44f7fc2
=> SES-4337 : Scroll to bottom ignores open keyboard

app/src/main/res/layout/blocked_contacts_preference.xml
[Fix for QA](https://optf.atlassian.net/browse/SES-4497?focusedCommentId=19442)
This PR updates _Blocked Contact_'s subtitle's text color to match with the other options.
=> SES-4497 : Blocked Contacts settings subtitle smaller font size than rest of the settings

app/src/main/java/org/thoughtcrime/securesms/database/Storage.kt
This PR fixes a issue with the control message for approving message requests by updating the thread after inserting the control message into the db.
=> SES-4560 : Message request acceptance - Control message doesn't show

app/src/main/java/org/thoughtcrime/securesms/reactions/any/ReactWithAnyEmojiDialogFragment.java
[SES-4533](https://optf.atlassian.net/browse/SES-4533)
The fragment is _not_ annotated for Hilt, so `getDefaultViewModelProviderFactory()` is not the Hilt VM factory. It falls back to the default, which tries to call a no-arg constructor and crashes.
This PR fixes the crash when opening the Emoji Picker (+) by annotating `ReactWithAnyEmojiDialogFragment` for Hilt (DI)
https://github.com/user-attachments/assets/3eecf4c3-a6ec-48b5-a57f-356ed4cebbd3
=> SES-4533 : Crash when tapping “+” in message emoji reactions bar

app/build.gradle.kts, app/src/main/java/org/session/libsession/utilities/ViewUtils.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageContentView.kt
- **SES-4530 : Read more button not displayed on message in some cases (#1483)**
- **Bump version to 1.27.1**
=> Prepare for release 1.27.1

app/src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.kt
[SES-4565](https://optf.atlassian.net/browse/SES-4565)
This PR fixes the issue on MediaPreviewActivity by handling new data received from a new intent coming from MediaOverViewActivity (All Media). 
After receiving new data, we find the position of the item based on its URI and then set that as the current pager page. If the look up fails, it calls `initializeMedia()` instead.
https://github.com/user-attachments/assets/29c82dbe-fedc-4074-b052-4fd01fe0fa7e
=> SES-4565 : Image Selection On The "All Media" Screen Can Open the Wrong Image

app/src/main/java/org/session/libsession/utilities/ViewUtils.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/messages/VisibleMessageContentView.kt
[SES-4614](https://optf.atlassian.net/browse/SES-4614)
This PR fixes the issue by always using the max bubble width instead of measured width.
I wasn't able to recreate the issue using my own messages, but some messages in the test community shows the Read more when it shouldn't.
=> SES-4614 : Read More Indicator Appears Erroneously

app/src/main/java/org/session/libsession/messaging/sending_receiving/MessageRequestResponseHandler.kt
This is a change that I forgot to add in after the blinded contact in config was merged in: basically, when your blind community message requests are accepted, they are supposed to be merged in one convo that was addressed by the contact's 05 address. This part is all good, but we also need to make sure we deleted those blinded contact from our configs so they don't produce empty threads.
=> [SES-3869] Fixed blinded contacts not deleted after accepting blind requests

app/src/main/java/org/session/libsession/messaging/sending_receiving/MessageRequestResponseHandler.kt, app/src/main/java/org/session/libsession/messaging/sending_receiving/ReceivedMessageHandler.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt
This PR addresses two issues:
1. "Accepting a message request" can be both explicit and implicit, we have always handled the explicit case but the implicit case is not handled correctly - as now the blinded MR needs special handling so if the implicit case (`VisibleMessage`) is not handled, it will trigger bugs described in SES-4626.
2. Improve UI logic around transitioning into the new conversation: no toast is shown and minimal animation is performed.
=> [SES-4626] - Blinded message request improvement

app/src/main/java/org/session/libsession/messaging/sending_receiving/pollers/OpenGroupPoller.kt
We should always query SOGS' outbox, regardless of we accept community request or not, as the outbox is the messages we **send**. This bug should have been here for a long time, except it's a wild west on prod where I think we also send a sync message to our swarm and it just accidentally works for this case but for very wrong reason. The root cause of the prod issue is the mismanagement of a blind address - given we have tidied up the addressing in the app it's no longer broken, so previously double-broken becomes broken... This PR address the another broken part.
=> [SES-4630] - Fixed community request outbox not synced

app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt, app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationViewModel.kt, app/src/main/java/org/thoughtcrime/securesms/ui/components/ConversationAppBar.kt, app/src/main/java/org/thoughtcrime/securesms/util/adapter/RecyclerViewUtils.kt
[SES-4388](https://optf.atlassian.net/browse/SES-4388)
Fixes based on the issues found [here](https://optf.atlassian.net/browse/QA-2536).
This PR changes how insets and heights are set for the spacer. The changes here removes double applied space for lower android versions (tested on Android 9) while retaining its behavior for newer versions.
This also includes a `fastScroll` flag for `handleScrollToBottom` since it might take a while to scroll to the bottom when sending attachments if the user is scrolled all the way up and it might mess with the `isNearBottom` flag. 
Sending a message will now scroll to the bottom immediately, like for attachments.
Also includes fixes to the inputBar issues for lower android versions.
=> SES-4388 : Auto scrolling issues

app/src/main/java/org/thoughtcrime/securesms/home/ConversationOptionsBottomSheet.kt
Block shouldn't be available for outgoing blinded message requests.
=> Shouldn't be able to block blinded MR

app/src/main/java/org/thoughtcrime/securesms/groups/GroupLeavingWorker.kt
This issue: a "XXX left the group" message not received (or not received reliably).
The root cause is we have tidied up the lifecycle of conversations including groups: essentially when the config data is removed, everything related to that resource will be cleaned up, this includes the group key used to encrypt the message to send to the group.
The "XXX left the group" message used to be send uncontrollably - meaning we fire it but never care if it's sent, but now we do because we are removing the resource from the config as soon as the "leave group process message" is sent. There's a non-trival chance that the notification message is not sent within this timeframe and thus gets cancelld by the group removal. This PR makes sure we send these two messages before we go ahead and remove the …
=> [SES-4642] - Fix group left notification message not sent

app/src/main/res/values/strings.xml
[Automated]
This PR includes the latest translations from Crowdin
Session uses the community-driven translation platform Crowdin for localization, anyone can contribute at https://getsession.org/translate
=> [Automated] Update translations from Crowdin
